streamsaver/config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'users#show'

  # providers
  get '/providers/new', to: 'providers#new', as: 'new_provider'
  # post 'providers', to: 'providers#create', as: 'providers'

  # shows
  get '/shows/new', to: 'shows#new', as: 'new_show'
  post '/shows', to: 'shows#create', as: 'create_show'
  get '/shows', to: 'shows#index', as: 'shows'

  # user login-signup
  post '/signup', to: 'users#create'
  get '/signup', to: 'users#new', as: 'users'

  get '/dashboard', to: 'users#show', as: 'user_dashboard'
  
  #session routes

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy', as: 'logout'

  # Testing date
  
  post '/set_date', to: 'users#set_date', as: 'set_date'

  #favorite routes
  get '/favorites/:id', to: 'favorites#show', as: 'favorite'
  delete '/favorites/:id', to: 'favorites#destroy', as: 'favorites'
  get '/plan', to: 'favorites#new', as: 'plan'
  post '/plan', to: 'favorites#create'
  post '/create_plan', to: 'favorites#create_plan'

end

streamsaver/app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-dark navbar-static-top navbar-expand-md">
    <div class="container">
        <button type="button" class="navbar-toggler collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> <span class="sr-only">Toggle navigation</span>
        </button> <%= link_to "Dashboard", user_dashboard_path, class: 'navbar-brand' %>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav mr-auto">
            <li class='nav-item'><%= link_to 'Add to Favorites', plan_path, class: 'nav-link' %></li>
            <li class='nav-item'><%= link_to 'Create a Show', new_show_path, class: 'nav-link' %></li>  
            <li class='nav-item'><%= link_to 'All Shows', shows_path, class: 'nav-link' %></li>  

            <li class='nav-item'>
                <%=form_tag logout_path do  %>
                    <%= submit_tag "Log Out"%>
                <%end%>
            </li> 
            </ul>
        </div>
    </div>
</nav>

streamsaver/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Stream Saver" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Stream Saver" %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= content_for?(:content) ? yield(:content) : yield %>
    </main>
  </body>
</html>