streamsaver/config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'users#show'

  # providers
  get '/providers/new', to: 'providers#new', as: 'new_provider'
  # post 'providers', to: 'providers#create', as: 'providers'

  # shows
  get '/shows/new', to: 'shows#new', as: 'new_show'
  post '/shows', to: 'shows#create', as: 'create_show'
  get '/shows', to: 'shows#index', as: 'shows'

  # user login-signup
  post '/signup', to: 'users#create'
  get '/signup', to: 'users#new', as: 'users'

  get '/dashboard', to: 'users#show', as: 'user_dashboard'
  
  #session routes

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy', as: 'logout'

  # Testing date
  
  post '/set_date', to: 'users#set_date', as: 'set_date'

  #favorite routes
  get '/favorites/:id', to: 'favorites#show', as: 'favorite'
  delete '/favorites/:id', to: 'favorites#destroy', as: 'favorites'
  get '/plan', to: 'favorites#new', as: 'plan'
  post '/plan', to: 'favorites#create'
  post '/create_plan', to: 'favorites#create_plan'

end

streamsaver/app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :show
    belongs_to :user

    def self.all_months
        ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
    end

    def self.full_month(month)
        full_months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
        full_months.select{|mon| 
            Favorite.all_months.find_index(month) == full_months.find_index(mon)}[0]
    end 

    def self.next_month(month)
        index = Favorite.all_months.find_index(month)
        if index == 11 
            new_index = 0 
        else 
            new_index = index + 1
        end 
        Favorite.all_months[new_index]
    end 

    def self.parse_months(favorites_to_months)
        
        groomed_favorites_to_month = favorites_to_months.keys.reduce({}) do |memo, fav_id_month|
            indexes = fav_id_month.split("_")
            favorite = Favorite.find(indexes[0].to_i)
            month = all_months[indexes[1].to_i]
            memo[favorite] = [] if memo[favorite] == nil
            memo[favorite] << month
            memo
        end
        groomed_favorites_to_month.each do |favorite, months|
            favorite.months = months.join(',')
            favorite.save
        end
    end

    def months_array
        self.months.split(',')
    end

    def self.month_to_number(month)
        self.all_months.find_index(month) + 1
    end 
    def self.number_to_month(number)
        self.all_months[number - 1]
    end

end

streamsaver/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  #before_action :logged_in?

  def show
    @favorite = Favorite.find(params[:id])
    @show = @favorite.show
  end

  def new 
    user = current_user
    shows = Show.all.select {|show| !user.shows.include?(show)}

    @shows_by_provider = Show.shows_by_provider(shows)
  end
  
  def create
    new_favorites = []
    
    show_params.each do |show_id|
        new_favorites << Favorite.create(user_id: current_user.id, show_id: show_id)
    end

    @favorites = new_favorites
    @all_months = Favorite.all_months

    render 'plan'
  end

  def destroy
    favorite = Favorite.destroy(params[:id])

    redirect_to user_dashboard_path
  end

  def create_plan
    Favorite.parse_months(params[:fav_months])
    redirect_to user_dashboard_path
  end

  private

  def show_params
    params.keys.reduce([]) do |memo, param|
      if param.start_with?('show')
        memo << params[param].to_i
      end
      memo
    end
  end

end

streamsaver/app/helpers/favorites_helper.rb
module FavoritesHelper
end

streamsaver/app/views/favorites/new.html.erb
<h1>Add to your favorites</h1>
<%= form_tag('/plan') do %>
  <% @shows_by_provider.each do |provider, shows|%>
    <h3 class="p-1 mb-2 bg-info text-white"> <%= provider %> </h3>
    <div class="form-row">
          <% shows.each do |show| %>
            <div class="col-sm-4 mb-3">
                <div class="form-check">
                  <%= check_box_tag("show_#{show.id}", value = show.id, checked = false) %>
                  <label class="form-check-label" for=<%=show.id%>>
                    <%=show.name%>
                  </label>
                </div>
                <img src=<%=show.image_url%> width="320" height="200">
            </div>
          <% end %>
    </div>
  <% end %>
  <div class="text-center mb-2 p-5" >
    <%= submit_tag ("Plan your stream!") %>
  </div>
<% end %>

streamsaver/app/views/favorites/plan.html.erb
<h1> Plan your watch flow </h1>
<%= form_tag('create_plan') do %>
<table>
  <tr>
    <th> Show Title </th>
    <% @all_months.each do |month| %>
        <th> <%= month %> </th>
    <% end %>
  </tr>

  <% @favorites.each do |favorite| %>
        <tr> 
          <td><%= favorite.show.name %> </td>
          <% @all_months.each_with_index do |month, month_index| %>
            <td> <%= check_box_tag "fav_months[#{favorite.id}_#{month_index}]" %> </td>
          <% end %>
          <!-- loop of checkboxes corresponding to months in td -->  
        </tr>
    <% end %>
</table>
<%= submit_tag %>
<% end %>

streamsaver/app/views/favorites/show.html.erb
<div class="text-center mb-2 p-3" >
    <h1 class="text-info"> <%= @show.name%> </h1>
    
    <div class="form-row">
        <div class="col-md-7 mb-3"><img src=<%=@show.image_url%> width="450" height="300"></div>
        <div class="col-md-5 text-left">
            <h3 class="p-3"> Streams on <%= @show.provider.name %> </h3>
            <p><%= @show.description %></p> 
            <h3>Planning to watch in: <span class="bg-info"> <%= @favorite.months %> </span> </h3>
        </div>
    </div>
    
    <div class="text-center mb-2 p-5">
        <%=form_tag(favorites_path(@favorite), method: :delete) do  %>
            <%= submit_tag "Remove from favorites"%>
        <%end%>
    </div>
  </div>