streamsaver/config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'users#show'

  # providers
  get '/providers/new', to: 'providers#new', as: 'new_provider'
  # post 'providers', to: 'providers#create', as: 'providers'

  # shows
  get '/shows/new', to: 'shows#new', as: 'new_show'
  post '/shows', to: 'shows#create', as: 'create_show'
  get '/shows', to: 'shows#index', as: 'shows'

  # user login-signup
  post '/signup', to: 'users#create'
  get '/signup', to: 'users#new', as: 'users'

  get '/dashboard', to: 'users#show', as: 'user_dashboard'
  
  #session routes

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy', as: 'logout'

  # Testing date
  
  post '/set_date', to: 'users#set_date', as: 'set_date'

  #favorite routes
  get '/favorites/:id', to: 'favorites#show', as: 'favorite'
  delete '/favorites/:id', to: 'favorites#destroy', as: 'favorites'
  get '/plan', to: 'favorites#new', as: 'plan'
  post '/plan', to: 'favorites#create'
  post '/create_plan', to: 'favorites#create_plan'

end

streamsaver/app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :favorites
    has_many :shows, through: :favorites

    validates :first_name, presence: true, length: {maximum: 15}
    validates :last_name, presence: true, length: {maximum: 15}
    validates :password, presence: true, length: {in: 5..15 }
    validates :password, confirmation: { case_sensitive: true}
    validates :email, presence: true, uniqueness: {case_sensitive: false}, format: { with: URI::MailTo::EMAIL_REGEXP }
    validates :phone_number, presence: true, format: { with: /\A\d{3}-\d{3}-\d{4}\z/, 
        message: "must be in xxx-xxx-xxxx format."}


    def shows_by_provider
        Show.shows_by_provider(self.shows)
    end

    #Helper method creates a hash of show names pointing to an array of months the user selected
    def favorites_by_month 
        new_hash = self.favorites.reduce({}) do |favorites_hash, favorite|
            favorites_hash[favorite] = favorite.months_array
            favorites_hash
        end
    end


    def display_favorites(month, current)
        current_favorites = []
        next_favorites = []
        future_favorites = []
        self.favorites.each do |favorite|
            months = favorite.months.split(",")
            next_month = Favorite.next_month(month)
            if months.include?(month)
                current_favorites << favorite
            elsif months.include?(next_month)
                next_favorites << favorite
            else   
                future_favorites << favorite
            end 
        end 
        if current == "current"
            current_favorites
        elsif current == "next"
            next_favorites
        elsif current == "future"
            future_favorites
        end
    end 

    def get_reminders(month, day)
       expiring_favorites = expiring_favorites(month, day)
       show_names = expiring_favorites.map {|favorite| favorite.show.name}
       provider_names = expiring_providers(expiring_favorites)
       reminder = []
       days_left = Time.days_in_month(month) - day.to_i
       if show_names != [] && day.to_i > 15
            shows = show_names.join(", ")
            reminder << "<strong>#{shows}</strong> will expire soon. You have <strong>#{days_left} days</strong> left to watch!"
       end 
       if provider_names != [] && day.to_i > 15
            providers = provider_names.join(", ")
            reminder << "You don't need <strong>#{providers}</strong> next month. Remember to deactivate your subscription in <strong>#{days_left} days</strong>."
       end
       reminder
    end 

    #Helper method to return a hash of of expiring shows (the key is the show and the value is its array of months)
    def expiring_favorites(month, day)
        favorite_hash = self.favorites_by_month.select do |favorite, month_array|
            Favorite.month_to_number(month_array.last) == month 
        end
        favorite_hash.keys
    end 

    #Helper method to get expiring providers by crossreferencing the hash of shows organized by providers against the list of shows expiring this month
    def expiring_providers(expiring_favorites)
        providers = []
        expiring_shows = expiring_favorites.map {|favorite| favorite.show}
        shows_by_provider.each do |provider, show_array|
            shows_in_common = show_array.select do |show|
                expiring_shows.include?(show)
            end
            if !shows_in_common.empty?
                providers << provider 
            end 
        end 
        providers
    end 

end

streamsaver/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in?, except: [:new, :create]
  
  def new
    @user = User.new
  end

  def login 
    @user
  end 

  def create
    @user = User.new(user_params)
      if @user.valid? 
        @user.save
        session[:user_id] = @user.id 
        redirect_to user_dashboard_path(@user)
      else 
        flash[:errors] = @user.errors.full_messages
        redirect_to users_path
      end 
  end

  def index 
  end 

  def show
    @user = current_user
    @current_month = session[:month] ? session[:month] : Favorite.number_to_month(Time.now.month)
    @next_month = Favorite.next_month(@current_month)
    @current_day = session[:day] ? session[:day] : Time.now.day
    @current_month_number = session[:month_number] ? session[:month_number] : Time.now.month
    @favorites_this_month = @user.display_favorites(@current_month, "current")
    @favorites_next_month = @user.display_favorites(@current_month, "next")
    @upcoming_favorites = @user.display_favorites(@current_month, "future")
    @reminders = @user.get_reminders(@current_month_number, @current_day)
    if @reminders.empty? 
      @reminders <<"Welcome, #{@user.first_name}! You have no messages."
    end 
  end

  def set_date
    user = current_user
    session[:day] = params[:date]["date(3i)"]
    
    month_number = params[:date]["date(2i)"].to_i
    session[:month_number] = month_number
    session[:month] = Favorite.all_months[month_number - 1]
    reminders = user.get_reminders(session[:month_number], session[:day])
    if !reminders.empty?
        UserMailer.notification_email(user, reminders).deliver_now
    end 
    redirect_to user_dashboard_path
  end

  private 

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :phone_number)
  end 
end

streamsaver/app/helpers/users_helper.rb
module UsersHelper
end

streamsaver/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

streamsaver/app/views/users/new.html.erb
<h1>Create a new user</h1>

<%if flash[:errors]%>
<%flash[:errors].each do |error|%>
<p><%=error%></p>
<%end%>
<%end%>

<%=form_for @user do |f| %>
<label>First Name: </label>
<%=f.text_field :first_name%>
<label>Last Name: </label>
<%=f.text_field :last_name%>
<br>
<label>Email: </label>
<%=f.text_field :email%>
<br>
<label>Password: </label>
<%=f.password_field :password%>
<label>Confirm Password: </label>
<%=f.password_field :password_confirmation%>
<br>
<label>Phone Number: </label>
<%=f.text_field :phone_number, value: "555-555-5555"%>
<br>
<br>
<%=f.submit "Create Account"%>
<%end%>

streamsaver/app/views/users/show.html.erb
<div class = "dashboard-container d-flex">
    <div class="messages d-flex">
           
                <%@reminders.each do |reminder|%>
                    <p><%=reminder.html_safe%></p>
                <%end%>
            
    </div>
    <div class="date-picker d-flex" >
        <p>Pick a mock date:</p>
        <br>
        <%= form_tag(set_date_path) do %>
            <%= date_select(:date, :date, default: { day: @current_day.to_i, month: @current_month_number }) %>
            <%= submit_tag %>
        <% end %>
    </div>
</div>

<div class = "dashboard-content">
    <div style="color:white;">
    <%if  @favorites_this_month != []%>
            <h3 class="p-1 mb-2 bg-info text-white">Current Shows (<%=Favorite.full_month(@current_month)%>)</h3>
            <div class="tv-block">
                <%@favorites_this_month.each do |favorite|%>
                    <div class = "column">
                        <a href=<%=favorite_path(favorite)%>> <img class="linked-image" src=<%=favorite.show.image_url%> width="300" height="200"></a>
                        <div class="tv-info">
                            <%=favorite.show.name%> | 
                            <%=favorite.show.provider.name%>
                        </div>
                    </div>
                <%end%>
            </div>
            <%end%>

    <%if @favorites_next_month != []%>
            <h3 class="p-1 mb-2 bg-info text-white">Coming Up (<%=Favorite.full_month(@next_month)%>)</h3>
            <div class="tv-block">
                <%@favorites_next_month.each do |favorite|%>
                    <div class = "column">
                        <a href=<%=favorite_path(favorite)%>> <img class="linked-image" src=<%=favorite.show.image_url%> width="300" height="200"></a>
                        <div class="tv-info">
                            <%=favorite.show.name%> | 
                            <%=favorite.show.provider.name%>
                        </div>
                    </div>
                <%end%>
            </div>
            <%end%>
        <%if @upcoming_favorites != []%>
        <h3 class="p-1 mb-2 bg-info text-white">Future Shows</h3>
        <div class="tv-block">
            <%@upcoming_favorites.each do |favorite|%>
                <div class="column">
                    <a href=<%=favorite_path(favorite)%>><img class="linked-image" src=<%=favorite.show.image_url%> width="300" height="200"></a>
                    <div class="tv-info">
                        <%=favorite.show.name%> | 
                        <%=favorite.show.provider.name%> | 
                        <%favorite.months.split(",").each do |month|%>
                            <%=Favorite.full_month(month)%>
                        <%end%>
                    </div>
                </div>
            <%end%>
        </div>
        <%end%>
    </div>
</div>